export const GET_USER_DATA = 'GET_USER_DATA'
export const UPDATE_XCD='UPDATE_XCD'
export const UPDATE_CHECKS='UPDATE_CHECKS' 
export const UPDATE_TOTAL='UPDATE_TOTAL' 
export const UPDATE_QRDETAIL='UPDATE_QRDETAIL' 
export const UPDATE_FX='UPDATE_FX' 
export const UPDATE_USER_DEPOSIT_RECORD='UPDATE_USER_DEPOSIT_RECORD' 
export const UPDATE_NOTIFICATION_STATUS = 'UPDATE_NOTIFICATION_STATUS';







//function
 //function

